-- MySQL Script generated by MySQL Workbench
-- Sun Mar 16 17:39:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema swp391healthy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `swp391healthy` ;

-- -----------------------------------------------------
-- Schema swp391healthy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `swp391healthy` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `swp391healthy` ;

-- -----------------------------------------------------
-- Table `swp391healthy`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`users` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`users` (
  `UserID` VARCHAR(36) NOT NULL,
  `Address` VARCHAR(100) NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NOT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `FullName` VARCHAR(100) NOT NULL,
  `Gender` ENUM('FEMALE', 'MALE', 'OTHER') NULL DEFAULT NULL,
  `HashedID` VARCHAR(255) NOT NULL,
  `isActive` BIT(1) NULL DEFAULT NULL,
  `isDeleted` BIT(1) NULL DEFAULT NULL,
  `IsVerified` BIT(1) NOT NULL,
  `PasswordHash` VARCHAR(255) NOT NULL,
  `PhoneNumber` VARCHAR(15) NULL DEFAULT NULL,
  `Role` ENUM('MANAGER', 'PARENT', 'PSYCHOLOGIST', 'STUDENT') NOT NULL,
  `TokenExpiration` DATETIME(6) NOT NULL,
  `UpdatedAt` DATETIME(6) NOT NULL,
  `VerificationToken` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UKjdfr6kjrxekx1j5vrr77rp44t` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`parents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`parents` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`parents` (
  `ParentID` VARCHAR(36) NOT NULL,
  `UserID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ParentID`),
  INDEX `FKj0gwsij677b838ipqcmrclxhy` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FKj0gwsij677b838ipqcmrclxhy`
    FOREIGN KEY (`UserID`)
    REFERENCES `swp391healthy`.`users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`students` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`students` (
  `StudentID` VARCHAR(36) NOT NULL,
  `AnxietyScore` DECIMAL(5,2) NULL DEFAULT NULL,
  `ClassName` VARCHAR(20) NULL DEFAULT NULL,
  `DepressionScore` DECIMAL(5,2) NULL DEFAULT NULL,
  `Grade` INT NULL DEFAULT NULL,
  `ParentID` VARCHAR(36) NULL DEFAULT NULL,
  `SchoolName` VARCHAR(100) NULL DEFAULT NULL,
  `StressScore` DECIMAL(5,2) NULL DEFAULT NULL,
  `UserID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`StudentID`),
  INDEX `FKciyagwdb0nowj7f0dyoia1k3t` (`ParentID` ASC) VISIBLE,
  INDEX `FKaengiastf6jkwmemijj3g2onv` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FKaengiastf6jkwmemijj3g2onv`
    FOREIGN KEY (`UserID`)
    REFERENCES `swp391healthy`.`users` (`UserID`),
  CONSTRAINT `FKciyagwdb0nowj7f0dyoia1k3t`
    FOREIGN KEY (`ParentID`)
    REFERENCES `swp391healthy`.`parents` (`ParentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`department` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`department` (
  `DepartmentID` VARCHAR(36) NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`DepartmentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`psychologists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`psychologists` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`psychologists` (
  `PsychologistID` VARCHAR(36) NOT NULL,
  `DepartmentID` VARCHAR(36) NULL DEFAULT NULL,
  `Status` ENUM('ACTIVE', 'DELETED', 'INACTIVE', 'ON_LEAVE') NOT NULL,
  `UserID` VARCHAR(36) NOT NULL,
  `YearsOfExperience` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PsychologistID`),
  INDEX `FK6socmrflubw3g1vrdx8hm8vml` (`DepartmentID` ASC) VISIBLE,
  INDEX `FKk8ad9rs4e4wbhcf7nxvf1c16n` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FK6socmrflubw3g1vrdx8hm8vml`
    FOREIGN KEY (`DepartmentID`)
    REFERENCES `swp391healthy`.`department` (`DepartmentID`),
  CONSTRAINT `FKk8ad9rs4e4wbhcf7nxvf1c16n`
    FOREIGN KEY (`UserID`)
    REFERENCES `swp391healthy`.`users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`timeslots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`timeslots` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`timeslots` (
  `TimeSlotsID` VARCHAR(36) NOT NULL,
  `booked` BIT(1) NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NOT NULL,
  `current_bookings` INT NOT NULL,
  `default_slot_id` VARCHAR(255) NULL DEFAULT NULL,
  `EndTime` TIME NOT NULL,
  `max_capacity` INT NOT NULL,
  `SlotDate` DATE NOT NULL,
  `SlotNumber` INT NOT NULL,
  `StartTime` TIME NOT NULL,
  `Status` ENUM('AVAILABLE', 'BOOKED', 'UNAVAILABLE') NOT NULL,
  `PsychologistID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`TimeSlotsID`),
  INDEX `FK9ece0eaadgo17qqksrlvif0gh` (`PsychologistID` ASC) VISIBLE,
  CONSTRAINT `FK9ece0eaadgo17qqksrlvif0gh`
    FOREIGN KEY (`PsychologistID`)
    REFERENCES `swp391healthy`.`psychologists` (`PsychologistID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`appointments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`appointments` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`appointments` (
  `AppointmentID` VARCHAR(36) NOT NULL,
  `CancellationReason` TEXT NULL DEFAULT NULL,
  `CheckInTime` DATETIME(6) NULL DEFAULT NULL,
  `CheckOutTime` DATETIME(6) NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `PsychologistID` VARCHAR(36) NOT NULL,
  `PsychologistNote` TEXT NULL DEFAULT NULL,
  `Rating` INT NULL DEFAULT NULL,
  `Status` ENUM('CANCELLED', 'COMPLETED', 'IN_PROGRESS', 'SCHEDULED') NULL DEFAULT NULL,
  `StudentID` VARCHAR(36) NOT NULL,
  `StudentNote` TEXT NULL DEFAULT NULL,
  `TimeSlotsID` VARCHAR(36) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`AppointmentID`),
  INDEX `FKmily3f3tgg2d14poosui8nvyt` (`PsychologistID` ASC) VISIBLE,
  INDEX `FK7j3kvglfjb20jbx6oubix5y9b` (`StudentID` ASC) VISIBLE,
  INDEX `FKayb7iw3wolqlcv0mjvub5bw2h` (`TimeSlotsID` ASC) VISIBLE,
  CONSTRAINT `FK7j3kvglfjb20jbx6oubix5y9b`
    FOREIGN KEY (`StudentID`)
    REFERENCES `swp391healthy`.`students` (`StudentID`),
  CONSTRAINT `FKayb7iw3wolqlcv0mjvub5bw2h`
    FOREIGN KEY (`TimeSlotsID`)
    REFERENCES `swp391healthy`.`timeslots` (`TimeSlotsID`),
  CONSTRAINT `FKmily3f3tgg2d14poosui8nvyt`
    FOREIGN KEY (`PsychologistID`)
    REFERENCES `swp391healthy`.`psychologists` (`PsychologistID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`article` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`article` (
  `ArticleID` VARCHAR(36) NOT NULL,
  `Content` TEXT NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `likes` INT NOT NULL,
  `Title` VARCHAR(100) NULL DEFAULT NULL,
  `AuthorID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ArticleID`),
  INDEX `FK6lu0nhcalisyhm83bb7kcwlhn` (`AuthorID` ASC) VISIBLE,
  CONSTRAINT `FK6lu0nhcalisyhm83bb7kcwlhn`
    FOREIGN KEY (`AuthorID`)
    REFERENCES `swp391healthy`.`users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`tags` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`tags` (
  `TagID` VARCHAR(36) NOT NULL,
  `TagName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`TagID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`articletags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`articletags` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`articletags` (
  `ArticleId` VARCHAR(36) NOT NULL,
  `TagId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ArticleId`, `TagId`),
  INDEX `FK211863rqolg9dby033aq5csuo` (`TagId` ASC) VISIBLE,
  CONSTRAINT `FK1p80k2gpjsimmemlg107oy41a`
    FOREIGN KEY (`ArticleId`)
    REFERENCES `swp391healthy`.`article` (`ArticleID`),
  CONSTRAINT `FK211863rqolg9dby033aq5csuo`
    FOREIGN KEY (`TagId`)
    REFERENCES `swp391healthy`.`tags` (`TagID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`categories` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`categories` (
  `CategoryID` VARCHAR(36) NOT NULL,
  `CategoryName` ENUM('ANXIETY', 'DEPRESSION', 'STRESS') NOT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`surveys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`surveys` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`surveys` (
  `SurveyID` VARCHAR(36) NOT NULL,
  `CategoryID` VARCHAR(36) NOT NULL,
  `CreatedAt` DATETIME(6) NOT NULL,
  `CreatedBy` VARCHAR(36) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `Details` TEXT NULL DEFAULT NULL,
  `Duration` VARCHAR(100) NULL DEFAULT NULL,
  `Status` ENUM('ACTIVE', 'CANCELLED', 'INACTIVE') NOT NULL,
  `SurveyName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`SurveyID`),
  INDEX `FKk4lykft9ydt37leirifqmsalt` (`CategoryID` ASC) VISIBLE,
  INDEX `FKo76oxa2c3q56tr77aknoeqjck` (`CreatedBy` ASC) VISIBLE,
  CONSTRAINT `FKk4lykft9ydt37leirifqmsalt`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `swp391healthy`.`categories` (`CategoryID`),
  CONSTRAINT `FKo76oxa2c3q56tr77aknoeqjck`
    FOREIGN KEY (`CreatedBy`)
    REFERENCES `swp391healthy`.`users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`programs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`programs` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`programs` (
  `ProgramID` VARCHAR(36) NOT NULL,
  `CreatedAt` DATETIME(6) NOT NULL,
  `DepartmentID` VARCHAR(36) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `Duration` INT NULL DEFAULT NULL,
  `EndDate` DATE NULL DEFAULT NULL,
  `FacilitatorID` VARCHAR(36) NOT NULL,
  `MeetingLink` VARCHAR(255) NULL DEFAULT NULL,
  `NumberParticipants` INT NULL DEFAULT NULL,
  `ProgramName` VARCHAR(100) NOT NULL,
  `Rating` INT NULL DEFAULT NULL,
  `StartDate` DATE NULL DEFAULT NULL,
  `Status` ENUM('ACTIVE', 'COMPLETED', 'DELETED', 'INACTIVE', 'IN_PROGRESS') NOT NULL,
  `AppointmentType` ENUM('OFFLINE', 'ONLINE') NOT NULL,
  `CreatedByUser` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ProgramID`),
  INDEX `FKd5ofntotwoedguak122qijufi` (`CreatedByUser` ASC) VISIBLE,
  INDEX `FK4jmg7ygekgx5spttenbdmx1kx` (`DepartmentID` ASC) VISIBLE,
  INDEX `FKsb6seu9egjvj1832rhwsi7awb` (`FacilitatorID` ASC) VISIBLE,
  CONSTRAINT `FK4jmg7ygekgx5spttenbdmx1kx`
    FOREIGN KEY (`DepartmentID`)
    REFERENCES `swp391healthy`.`department` (`DepartmentID`),
  CONSTRAINT `FKd5ofntotwoedguak122qijufi`
    FOREIGN KEY (`CreatedByUser`)
    REFERENCES `swp391healthy`.`users` (`UserID`),
  CONSTRAINT `FKsb6seu9egjvj1832rhwsi7awb`
    FOREIGN KEY (`FacilitatorID`)
    REFERENCES `swp391healthy`.`psychologists` (`PsychologistID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`comments` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`comments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `AppointmentID` VARCHAR(36) NULL DEFAULT NULL,
  `ArticleID` VARCHAR(36) NULL DEFAULT NULL,
  `content` TEXT NOT NULL,
  `createdAt` DATETIME(6) NULL DEFAULT NULL,
  `ProgramID` VARCHAR(36) NULL DEFAULT NULL,
  `Rating` INT NULL DEFAULT NULL,
  `SurveyID` VARCHAR(36) NULL DEFAULT NULL,
  `Article` VARCHAR(36) NULL DEFAULT NULL,
  `UserID` VARCHAR(36) NOT NULL,
  `ParentCommentID` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKoav7rdyjaf6oawhs06ga6ekd1` (`AppointmentID` ASC) VISIBLE,
  INDEX `FKmhbf6s5paxfvy7630cbvufmvo` (`Article` ASC) VISIBLE,
  INDEX `FKqrwtn1chcp7ocoaummlh3bf39` (`UserID` ASC) VISIBLE,
  INDEX `FK278qt707s8c9ip47fh8pwqtc3` (`ParentCommentID` ASC) VISIBLE,
  INDEX `FKscm9u96d2vbmku532q313k1uu` (`ProgramID` ASC) VISIBLE,
  INDEX `FKgfyd4yb9t9sytdwwcmt0mik8b` (`SurveyID` ASC) VISIBLE,
  CONSTRAINT `FK278qt707s8c9ip47fh8pwqtc3`
    FOREIGN KEY (`ParentCommentID`)
    REFERENCES `swp391healthy`.`comments` (`id`),
  CONSTRAINT `FKgfyd4yb9t9sytdwwcmt0mik8b`
    FOREIGN KEY (`SurveyID`)
    REFERENCES `swp391healthy`.`surveys` (`SurveyID`),
  CONSTRAINT `FKmhbf6s5paxfvy7630cbvufmvo`
    FOREIGN KEY (`Article`)
    REFERENCES `swp391healthy`.`article` (`ArticleID`),
  CONSTRAINT `FKoav7rdyjaf6oawhs06ga6ekd1`
    FOREIGN KEY (`AppointmentID`)
    REFERENCES `swp391healthy`.`appointments` (`AppointmentID`),
  CONSTRAINT `FKqrwtn1chcp7ocoaummlh3bf39`
    FOREIGN KEY (`UserID`)
    REFERENCES `swp391healthy`.`users` (`UserID`),
  CONSTRAINT `FKscm9u96d2vbmku532q313k1uu`
    FOREIGN KEY (`ProgramID`)
    REFERENCES `swp391healthy`.`programs` (`ProgramID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`default_time_slots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`default_time_slots` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`default_time_slots` (
  `slotId` VARCHAR(255) NOT NULL,
  `endTime` TIME NOT NULL,
  `period` VARCHAR(255) NOT NULL,
  `startTime` TIME NOT NULL,
  PRIMARY KEY (`slotId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`feedback` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`feedback` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `Comment` TEXT NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `Rating` INT NULL DEFAULT NULL,
  `AppointmentID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK5iy6h8l31n2f00kwdewg3n07b` (`AppointmentID` ASC) VISIBLE,
  CONSTRAINT `FK5iy6h8l31n2f00kwdewg3n07b`
    FOREIGN KEY (`AppointmentID`)
    REFERENCES `swp391healthy`.`appointments` (`AppointmentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`notification_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`notification_schedule` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`notification_schedule` (
  `id` VARCHAR(255) NOT NULL,
  `notification_day` TINYINT NULL DEFAULT NULL,
  `notification_time` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`notifications` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`notifications` (
  `NotificationID` VARCHAR(36) NOT NULL,
  `AppointmentID` VARCHAR(36) NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsRead` BIT(1) NULL DEFAULT NULL,
  `Message` TEXT NOT NULL,
  `ProgramID` VARCHAR(36) NULL DEFAULT NULL,
  `SurveyID` VARCHAR(36) NULL DEFAULT NULL,
  `Title` VARCHAR(255) NOT NULL,
  `Type` ENUM('APPOINTMENT', 'DONE', 'NOTIFICATION_TYPE', 'ON_LEAVE', 'PROGRAM', 'SURVEY') NOT NULL,
  `UserID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`NotificationID`),
  INDEX `FKgc9xl1x8fpo955vsq8kb3b566` (`AppointmentID` ASC) VISIBLE,
  INDEX `FKnnjwgcebdpf2w50ecjmasadya` (`ProgramID` ASC) VISIBLE,
  INDEX `FKk7ft32q0hcu6vwgdndm15o5ji` (`SurveyID` ASC) VISIBLE,
  INDEX `FK689wccaxeicnjy9vjaqks20ya` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FK689wccaxeicnjy9vjaqks20ya`
    FOREIGN KEY (`UserID`)
    REFERENCES `swp391healthy`.`users` (`UserID`),
  CONSTRAINT `FKgc9xl1x8fpo955vsq8kb3b566`
    FOREIGN KEY (`AppointmentID`)
    REFERENCES `swp391healthy`.`appointments` (`AppointmentID`),
  CONSTRAINT `FKk7ft32q0hcu6vwgdndm15o5ji`
    FOREIGN KEY (`SurveyID`)
    REFERENCES `swp391healthy`.`surveys` (`SurveyID`),
  CONSTRAINT `FKnnjwgcebdpf2w50ecjmasadya`
    FOREIGN KEY (`ProgramID`)
    REFERENCES `swp391healthy`.`programs` (`ProgramID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`programparticipation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`programparticipation` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`programparticipation` (
  `ParticipationID` VARCHAR(36) NOT NULL,
  `EndDate` DATE NULL DEFAULT NULL,
  `ProgramID` VARCHAR(36) NOT NULL,
  `StartDate` DATE NOT NULL,
  `Status` ENUM('CANCELLED', 'COMPLETED', 'JOINED') NOT NULL,
  `StudentID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ParticipationID`),
  INDEX `FK19bqmcxun4kulmgtpwlhlf65i` (`ProgramID` ASC) VISIBLE,
  INDEX `FKcqkowhb5ekatyig1sjvrkj6ba` (`StudentID` ASC) VISIBLE,
  CONSTRAINT `FK19bqmcxun4kulmgtpwlhlf65i`
    FOREIGN KEY (`ProgramID`)
    REFERENCES `swp391healthy`.`programs` (`ProgramID`),
  CONSTRAINT `FKcqkowhb5ekatyig1sjvrkj6ba`
    FOREIGN KEY (`StudentID`)
    REFERENCES `swp391healthy`.`students` (`StudentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`programschedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`programschedule` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`programschedule` (
  `ScheduleID` VARCHAR(36) NOT NULL,
  `DayOfWeek` VARCHAR(10) NOT NULL,
  `EndTime` TIME NOT NULL,
  `ProgramID` VARCHAR(36) NOT NULL,
  `StartTime` TIME NOT NULL,
  `Program` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ScheduleID`),
  INDEX `FKnq04h0tks92lngk23in256c6d` (`Program` ASC) VISIBLE,
  CONSTRAINT `FKnq04h0tks92lngk23in256c6d`
    FOREIGN KEY (`Program`)
    REFERENCES `swp391healthy`.`programs` (`ProgramID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`programtags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`programtags` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`programtags` (
  `ProgramId` VARCHAR(36) NOT NULL,
  `TagId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ProgramId`, `TagId`),
  INDEX `FKsf4tt0sadfbmidngtelynbbpl` (`TagId` ASC) VISIBLE,
  CONSTRAINT `FKqe3rsyoj9xkw039g2gl1wkfuh`
    FOREIGN KEY (`ProgramId`)
    REFERENCES `swp391healthy`.`programs` (`ProgramID`),
  CONSTRAINT `FKsf4tt0sadfbmidngtelynbbpl`
    FOREIGN KEY (`TagId`)
    REFERENCES `swp391healthy`.`tags` (`TagID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`psychologist_kpi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`psychologist_kpi` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`psychologist_kpi` (
  `id` VARCHAR(255) NOT NULL,
  `achieved_slots` INT NULL DEFAULT NULL,
  `month` INT NOT NULL,
  `psychologist_id` VARCHAR(255) NULL DEFAULT NULL,
  `target_slots` INT NULL DEFAULT NULL,
  `year` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`refreshtoken`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`refreshtoken` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`refreshtoken` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ExpiresAt` DATETIME(6) NOT NULL,
  `HashedToken` VARCHAR(255) NOT NULL,
  `UserID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKpxtlubptdust15wrm4k48fr4i` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FKpxtlubptdust15wrm4k48fr4i`
    FOREIGN KEY (`UserID`)
    REFERENCES `swp391healthy`.`users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`resettokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`resettokens` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`resettokens` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ExpiresAt` DATETIME(6) NOT NULL,
  `HashedToken` VARCHAR(255) NOT NULL,
  `UserID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKr4ep844po8w05gs6f2niidgfh` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FKr4ep844po8w05gs6f2niidgfh`
    FOREIGN KEY (`UserID`)
    REFERENCES `swp391healthy`.`users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`surveyquestions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`surveyquestions` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`surveyquestions` (
  `QuestionID` VARCHAR(36) NOT NULL,
  `CategoryID` VARCHAR(36) NULL DEFAULT NULL,
  `QuestionText` TEXT NOT NULL,
  `SurveyID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`QuestionID`),
  INDEX `FK3mu1ylyqne2p4vboi456v9phv` (`CategoryID` ASC) VISIBLE,
  INDEX `FKb3qeg2ym9kg6byybvra3mql58` (`SurveyID` ASC) VISIBLE,
  CONSTRAINT `FK3mu1ylyqne2p4vboi456v9phv`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `swp391healthy`.`categories` (`CategoryID`),
  CONSTRAINT `FKb3qeg2ym9kg6byybvra3mql58`
    FOREIGN KEY (`SurveyID`)
    REFERENCES `swp391healthy`.`surveys` (`SurveyID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`surveyquestionoptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`surveyquestionoptions` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`surveyquestionoptions` (
  `OptionID` VARCHAR(36) NOT NULL,
  `OptionText` TEXT NOT NULL,
  `QuestionID` VARCHAR(36) NOT NULL,
  `Score` INT NULL DEFAULT NULL,
  PRIMARY KEY (`OptionID`),
  INDEX `FK4q67dge0qfux5g9homnyd9mp8` (`QuestionID` ASC) VISIBLE,
  CONSTRAINT `FK4q67dge0qfux5g9homnyd9mp8`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `swp391healthy`.`surveyquestions` (`QuestionID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`surveyresult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`surveyresult` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`surveyresult` (
  `ResultID` VARCHAR(36) NOT NULL,
  `CreatedAt` DATETIME(6) NOT NULL,
  `MaxScore` INT NULL DEFAULT NULL,
  `Result` INT NULL DEFAULT NULL,
  `StudentID` VARCHAR(36) NOT NULL,
  `SurveyID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ResultID`),
  INDEX `FK3vqby6ohalw8g63q5gg3f4tr9` (`StudentID` ASC) VISIBLE,
  INDEX `FKcspdsjw75p9bcy2x3uahgsm99` (`SurveyID` ASC) VISIBLE,
  CONSTRAINT `FK3vqby6ohalw8g63q5gg3f4tr9`
    FOREIGN KEY (`StudentID`)
    REFERENCES `swp391healthy`.`students` (`StudentID`),
  CONSTRAINT `FKcspdsjw75p9bcy2x3uahgsm99`
    FOREIGN KEY (`SurveyID`)
    REFERENCES `swp391healthy`.`surveys` (`SurveyID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`surveyquestionoptionschoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`surveyquestionoptionschoices` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`surveyquestionoptionschoices` (
  `OptionsChoices` VARCHAR(36) NOT NULL,
  `CreatedAt` DATETIME(6) NOT NULL,
  `OptionID` VARCHAR(36) NOT NULL,
  `QuestionID` VARCHAR(36) NOT NULL,
  `ResultID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`OptionsChoices`),
  INDEX `FK3qehlh5up2l2r9vewfkrwl24w` (`OptionID` ASC) VISIBLE,
  INDEX `FK6qx6b2f8wgqsmntyotpqwu39g` (`QuestionID` ASC) VISIBLE,
  INDEX `FK350lkbwomn7xo1h3sss4ye7xj` (`ResultID` ASC) VISIBLE,
  CONSTRAINT `FK350lkbwomn7xo1h3sss4ye7xj`
    FOREIGN KEY (`ResultID`)
    REFERENCES `swp391healthy`.`surveyresult` (`ResultID`),
  CONSTRAINT `FK3qehlh5up2l2r9vewfkrwl24w`
    FOREIGN KEY (`OptionID`)
    REFERENCES `swp391healthy`.`surveyquestionoptions` (`OptionID`),
  CONSTRAINT `FK6qx6b2f8wgqsmntyotpqwu39g`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `swp391healthy`.`surveyquestions` (`QuestionID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `swp391healthy`.`userlogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swp391healthy`.`userlogs` ;

CREATE TABLE IF NOT EXISTS `swp391healthy`.`userlogs` (
  `LogID` VARCHAR(36) NOT NULL,
  `IPAddress` VARCHAR(50) NULL DEFAULT NULL,
  `LoginTime` DATETIME(6) NULL DEFAULT NULL,
  `UserID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`LogID`),
  INDEX `FKct2vgnj582notleijgl3l3mkj` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FKct2vgnj582notleijgl3l3mkj`
    FOREIGN KEY (`UserID`)
    REFERENCES `swp391healthy`.`users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
