-- MySQL Script generated by MySQL Workbench
-- Tue Feb 18 11:36:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema swp391healthymv
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema swp391healthy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema swp391healthy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `swp391healthy` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `swp391healthy` ;

-- -----------------------------------------------------
-- Table `swp391healthy`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`categories` (
  `CategoryID` VARCHAR(36) NOT NULL,
  `CategoryName` ENUM('Anxiety', 'Depression', 'Stress') NOT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`users` (
  `UserID` VARCHAR(36) NOT NULL,
  `Address` VARCHAR(100) NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NOT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `FullName` VARCHAR(100) NOT NULL,
  `Gender` ENUM('Male', 'Female', 'Other') NULL DEFAULT NULL,
  `IsVerified` BIT(1) NOT NULL,
  `PasswordHash` VARCHAR(255) NOT NULL,
  `PhoneNumber` VARCHAR(15) NULL DEFAULT NULL,
  `ResetToken` VARCHAR(255) NULL DEFAULT NULL,
  `ResetTokenExpiry` DATETIME(6) NULL DEFAULT NULL,
  `Role` ENUM('MANAGER', 'PARENT', 'PSYCHOLOGIST', 'STUDENT') NOT NULL,
  `TokenExpiration` DATETIME(6) NOT NULL,
  `UpdatedAt` DATETIME(6) NOT NULL,
  `Username` VARCHAR(50) NOT NULL,
  `VerificationToken` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UK9cw87ffd4i55ki0qpkwu63er` (`Username` ASC) VISIBLE,
  UNIQUE INDEX `UKikxg9koctpmqub6afe9tlal14` (`Address` ASC) VISIBLE,
  UNIQUE INDEX `UKjdfr6kjrxekx1j5vrr77rp44t` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`surveys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`surveys` (
  `SurveyID` VARCHAR(36) NOT NULL,
  `CategoryID` VARCHAR(36) NOT NULL,
  `CreatedAt` DATETIME(6) NOT NULL,
  `CreatedBy` VARCHAR(36) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `Status` ENUM('Unfinished', 'Finished', 'Cancelled') NOT NULL,
  `SurveyName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`SurveyID`),
  INDEX `FKk4lykft9ydt37leirifqmsalt` (`CategoryID` ASC) VISIBLE,
  INDEX `FKo76oxa2c3q56tr77aknoeqjck` (`CreatedBy` ASC) VISIBLE,
  CONSTRAINT `FKk4lykft9ydt37leirifqmsalt`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `swp391healthy`.`categories` (`CategoryID`),
  CONSTRAINT `FKo76oxa2c3q56tr77aknoeqjck`
    FOREIGN KEY (`CreatedBy`)
    REFERENCES `swp391healthy`.`users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`surveyquestions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`surveyquestions` (
  `QuestionID` VARCHAR(36) NOT NULL,
  `CategoryID` VARCHAR(36) NULL DEFAULT NULL,
  `QuestionText` TEXT NOT NULL,
  `SurveyID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`QuestionID`),
  INDEX `FK3mu1ylyqne2p4vboi456v9phv` (`CategoryID` ASC) VISIBLE,
  INDEX `FKb3qeg2ym9kg6byybvra3mql58` (`SurveyID` ASC) VISIBLE,
  CONSTRAINT `FK3mu1ylyqne2p4vboi456v9phv`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `swp391healthy`.`categories` (`CategoryID`),
  CONSTRAINT `FKb3qeg2ym9kg6byybvra3mql58`
    FOREIGN KEY (`SurveyID`)
    REFERENCES `swp391healthy`.`surveys` (`SurveyID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`answers` (
  `AnswerID` VARCHAR(36) NOT NULL,
  `Answer` TEXT NOT NULL,
  `QuestionID` VARCHAR(36) NOT NULL,
  `Score` INT NULL DEFAULT NULL,
  PRIMARY KEY (`AnswerID`),
  INDEX `FKryr8kigvj5aw9w6ilkvmrht5q` (`QuestionID` ASC) VISIBLE,
  CONSTRAINT `FKryr8kigvj5aw9w6ilkvmrht5q`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `swp391healthy`.`surveyquestions` (`QuestionID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`parents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`parents` (
  `ParentID` VARCHAR(36) NOT NULL,
  `UserID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ParentID`),
  INDEX `FKj0gwsij677b838ipqcmrclxhy` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FKj0gwsij677b838ipqcmrclxhy`
    FOREIGN KEY (`UserID`)
    REFERENCES `swp391healthy`.`users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`students` (
  `StudentID` VARCHAR(36) NOT NULL,
  `AnxietyScore` INT NULL DEFAULT NULL,
  `ClassName` VARCHAR(20) NULL DEFAULT NULL,
  `DepressionScore` INT NULL DEFAULT NULL,
  `Grade` INT NULL DEFAULT NULL,
  `ParentID` VARCHAR(36) NOT NULL,
  `SchoolName` VARCHAR(100) NULL DEFAULT NULL,
  `StressScore` INT NULL DEFAULT NULL,
  `UserID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`StudentID`),
  INDEX `FKciyagwdb0nowj7f0dyoia1k3t` (`ParentID` ASC) VISIBLE,
  INDEX `FKaengiastf6jkwmemijj3g2onv` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FKaengiastf6jkwmemijj3g2onv`
    FOREIGN KEY (`UserID`)
    REFERENCES `swp391healthy`.`users` (`UserID`),
  CONSTRAINT `FKciyagwdb0nowj7f0dyoia1k3t`
    FOREIGN KEY (`ParentID`)
    REFERENCES `swp391healthy`.`parents` (`ParentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`department` (
  `DepartmentID` VARCHAR(36) NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`DepartmentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`psychologists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`psychologists` (
  `PsychologistID` VARCHAR(36) NOT NULL,
  `DepartmentID` VARCHAR(36) NULL DEFAULT NULL,
  `Status` ENUM('Active', 'Inactive', 'OnLeave') NOT NULL,
  `UserID` VARCHAR(36) NOT NULL,
  `YearsOfExperience` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PsychologistID`),
  INDEX `FK6socmrflubw3g1vrdx8hm8vml` (`DepartmentID` ASC) VISIBLE,
  INDEX `FKk8ad9rs4e4wbhcf7nxvf1c16n` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FK6socmrflubw3g1vrdx8hm8vml`
    FOREIGN KEY (`DepartmentID`)
    REFERENCES `swp391healthy`.`department` (`DepartmentID`),
  CONSTRAINT `FKk8ad9rs4e4wbhcf7nxvf1c16n`
    FOREIGN KEY (`UserID`)
    REFERENCES `swp391healthy`.`users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`timeslots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`timeslots` (
  `TimeSlotsID` VARCHAR(36) NOT NULL,
  `CreatedAt` DATETIME(6) NOT NULL,
  `EndTime` TIME NOT NULL,
  `SlotDate` DATE NOT NULL,
  `SlotNumber` INT NOT NULL,
  `StartTime` TIME NOT NULL,
  `Status` ENUM('Available', 'Booked') NOT NULL,
  `PsychologistID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`TimeSlotsID`),
  INDEX `FK9ece0eaadgo17qqksrlvif0gh` (`PsychologistID` ASC) VISIBLE,
  CONSTRAINT `FK9ece0eaadgo17qqksrlvif0gh`
    FOREIGN KEY (`PsychologistID`)
    REFERENCES `swp391healthy`.`psychologists` (`PsychologistID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`appointments` (
  `AppointmentID` VARCHAR(36) NOT NULL,
  `CheckInTime` DATETIME(6) NULL DEFAULT NULL,
  `CheckOutTime` DATETIME(6) NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `Feedback` TEXT NULL DEFAULT NULL,
  `PsychologistID` VARCHAR(36) NOT NULL,
  `PsychologistNote` TEXT NULL DEFAULT NULL,
  `Status` ENUM('Cancelled', 'Completed', 'InProgress', 'Scheduled') NULL DEFAULT NULL,
  `StudentID` VARCHAR(36) NOT NULL,
  `StudentNote` TEXT NULL DEFAULT NULL,
  `TimeSlotsID` VARCHAR(36) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`AppointmentID`),
  INDEX `FKmily3f3tgg2d14poosui8nvyt` (`PsychologistID` ASC) VISIBLE,
  INDEX `FK7j3kvglfjb20jbx6oubix5y9b` (`StudentID` ASC) VISIBLE,
  INDEX `FKayb7iw3wolqlcv0mjvub5bw2h` (`TimeSlotsID` ASC) VISIBLE,
  CONSTRAINT `FK7j3kvglfjb20jbx6oubix5y9b`
    FOREIGN KEY (`StudentID`)
    REFERENCES `swp391healthy`.`students` (`StudentID`),
  CONSTRAINT `FKayb7iw3wolqlcv0mjvub5bw2h`
    FOREIGN KEY (`TimeSlotsID`)
    REFERENCES `swp391healthy`.`timeslots` (`TimeSlotsID`),
  CONSTRAINT `FKmily3f3tgg2d14poosui8nvyt`
    FOREIGN KEY (`PsychologistID`)
    REFERENCES `swp391healthy`.`psychologists` (`PsychologistID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`article` (
  `ArticleID` VARCHAR(36) NOT NULL,
  `Content` TEXT NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(36) NULL DEFAULT NULL,
  `Title` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ArticleID`),
  INDEX `FK4hogxqsoqr8iyerohcyrfrmvv` (`CreatedBy` ASC) VISIBLE,
  CONSTRAINT `FK4hogxqsoqr8iyerohcyrfrmvv`
    FOREIGN KEY (`CreatedBy`)
    REFERENCES `swp391healthy`.`users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`notifications` (
  `NotificationID` VARCHAR(36) NOT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsRead` BIT(1) NULL DEFAULT NULL,
  `Message` TEXT NOT NULL,
  `Title` VARCHAR(255) NOT NULL,
  `Type` ENUM('Appointment', 'Survey', 'Program', 'Done') NOT NULL,
  `UserID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`NotificationID`),
  INDEX `FK689wccaxeicnjy9vjaqks20ya` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FK689wccaxeicnjy9vjaqks20ya`
    FOREIGN KEY (`UserID`)
    REFERENCES `swp391healthy`.`users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`programs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`programs` (
  `ProgramID` VARCHAR(36) NOT NULL,
  `CreatedAt` DATETIME(6) NOT NULL,
  `DepartmentID` VARCHAR(36) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `Duration` INT NULL DEFAULT NULL,
  `FacilitatorID` VARCHAR(36) NOT NULL,
  `MeetingLink` VARCHAR(255) NULL DEFAULT NULL,
  `NumberParticipants` INT NULL DEFAULT NULL,
  `ProgramName` VARCHAR(100) NOT NULL,
  `StartDate` DATE NULL DEFAULT NULL,
  `Status` ENUM('Active', 'Inactive') NOT NULL,
  `AppointmentType` ENUM('Offline', 'Online') NOT NULL,
  PRIMARY KEY (`ProgramID`),
  INDEX `FK4jmg7ygekgx5spttenbdmx1kx` (`DepartmentID` ASC) VISIBLE,
  INDEX `FKsb6seu9egjvj1832rhwsi7awb` (`FacilitatorID` ASC) VISIBLE,
  CONSTRAINT `FK4jmg7ygekgx5spttenbdmx1kx`
    FOREIGN KEY (`DepartmentID`)
    REFERENCES `swp391healthy`.`department` (`DepartmentID`),
  CONSTRAINT `FKsb6seu9egjvj1832rhwsi7awb`
    FOREIGN KEY (`FacilitatorID`)
    REFERENCES `swp391healthy`.`psychologists` (`PsychologistID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`programparticipation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`programparticipation` (
  `ParticipationID` VARCHAR(36) NOT NULL,
  `EndDate` DATE NULL DEFAULT NULL,
  `ProgramID` VARCHAR(36) NOT NULL,
  `StartDate` DATE NOT NULL,
  `Status` ENUM('Cancelled', 'Completed', 'Joined') NOT NULL,
  `StudentID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ParticipationID`),
  INDEX `FK19bqmcxun4kulmgtpwlhlf65i` (`ProgramID` ASC) VISIBLE,
  INDEX `FKcqkowhb5ekatyig1sjvrkj6ba` (`StudentID` ASC) VISIBLE,
  CONSTRAINT `FK19bqmcxun4kulmgtpwlhlf65i`
    FOREIGN KEY (`ProgramID`)
    REFERENCES `swp391healthy`.`programs` (`ProgramID`),
  CONSTRAINT `FKcqkowhb5ekatyig1sjvrkj6ba`
    FOREIGN KEY (`StudentID`)
    REFERENCES `swp391healthy`.`students` (`StudentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`programschedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`programschedule` (
  `ScheduleID` VARCHAR(36) NOT NULL,
  `DayOfWeek` VARCHAR(10) NOT NULL,
  `EndTime` TIME NOT NULL,
  `ProgramID` VARCHAR(36) NOT NULL,
  `StartTime` TIME NOT NULL,
  PRIMARY KEY (`ScheduleID`),
  INDEX `FK7cmhqcejobhnshmb1eeiok17u` (`ProgramID` ASC) VISIBLE,
  CONSTRAINT `FK7cmhqcejobhnshmb1eeiok17u`
    FOREIGN KEY (`ProgramID`)
    REFERENCES `swp391healthy`.`programs` (`ProgramID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`tags` (
  `TagID` VARCHAR(36) NOT NULL,
  `TagName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`TagID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`programtags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`programtags` (
  `ProgramId` VARCHAR(36) NOT NULL,
  `TagId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ProgramId`, `TagId`),
  INDEX `FKsf4tt0sadfbmidngtelynbbpl` (`TagId` ASC) VISIBLE,
  CONSTRAINT `FKqe3rsyoj9xkw039g2gl1wkfuh`
    FOREIGN KEY (`ProgramId`)
    REFERENCES `swp391healthy`.`programs` (`ProgramID`),
  CONSTRAINT `FKsf4tt0sadfbmidngtelynbbpl`
    FOREIGN KEY (`TagId`)
    REFERENCES `swp391healthy`.`tags` (`TagID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`refreshtoken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`refreshtoken` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ExpiresAt` DATETIME(6) NOT NULL,
  `HashedToken` VARCHAR(255) NOT NULL,
  `UserID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKpxtlubptdust15wrm4k48fr4i` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FKpxtlubptdust15wrm4k48fr4i`
    FOREIGN KEY (`UserID`)
    REFERENCES `swp391healthy`.`users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`surveyresults`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`surveyresults` (
  `ResultID` VARCHAR(36) NOT NULL,
  `AnswerID` VARCHAR(36) NOT NULL,
  `QuestionID` VARCHAR(36) NOT NULL,
  `StudentID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ResultID`),
  INDEX `FKjs72wj2vwxl45cg2walj44dg5` (`AnswerID` ASC) VISIBLE,
  INDEX `FK8t68w18aa6owt2opherlwv9vk` (`QuestionID` ASC) VISIBLE,
  INDEX `FK678llvs17bf7jg075j6lh9e1q` (`StudentID` ASC) VISIBLE,
  CONSTRAINT `FK678llvs17bf7jg075j6lh9e1q`
    FOREIGN KEY (`StudentID`)
    REFERENCES `swp391healthy`.`students` (`StudentID`),
  CONSTRAINT `FK8t68w18aa6owt2opherlwv9vk`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `swp391healthy`.`surveyquestions` (`QuestionID`),
  CONSTRAINT `FKjs72wj2vwxl45cg2walj44dg5`
    FOREIGN KEY (`AnswerID`)
    REFERENCES `swp391healthy`.`answers` (`AnswerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `swp391healthy`.`userlogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `swp391healthy`.`userlogs` (
  `LogID` VARCHAR(36) NOT NULL,
  `IPAddress` VARCHAR(50) NULL DEFAULT NULL,
  `LoginTime` DATETIME(6) NULL DEFAULT NULL,
  `UserID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`LogID`),
  INDEX `FKct2vgnj582notleijgl3l3mkj` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FKct2vgnj582notleijgl3l3mkj`
    FOREIGN KEY (`UserID`)
    REFERENCES `swp391healthy`.`users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
