version: '3.7'
services:
  db:
      image: mysql:8.4.3
      environment:
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: SWP391Healthy
      ports:
        - "3307:3306"

