[build]
builder = "NIXPACKS"
buildCommand = "echo 'Building via Dockerfile'"

[deploy]
startCommand = "echo 'Starting via Dockerfile'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[metrics]
port = 8080
path = "/actuator/prometheus"

[resource]
cpu = 0.5
memory = 512
numReplicas = 1

[env]
SPRING_PROFILES_ACTIVE = "prod"
JAVA_TOOL_OPTIONS = "-XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=70 -XX:+UseContainerSupport -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+ParallelRefProcEnabled -XX:MaxTenuringThreshold=1 -XX:+DisableExplicitGC -Djava.security.egd=file:/dev/./urandom -Dserver.tomcat.max-threads=50 -Dspring.jmx.enabled=false -Dspring.main.lazy-initialization=true" 