-- MySQL Script generated by MySQL Workbench
-- Sun Feb 16 15:12:39 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema localhost
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema swp391healthy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `swp391healthy` ;

-- -----------------------------------------------------
-- Schema swp391healthy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `swp391healthy` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `swp391healthy` ;

-- -----------------------------------------------------
-- Table `answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `answers` ;

CREATE TABLE IF NOT EXISTS `answers` (
  `AnswerID` VARCHAR(36) NOT NULL,
  `Answer` TEXT NOT NULL,
  `QuestionID` VARCHAR(36) NOT NULL,
  `Score` INT NULL DEFAULT NULL,
  PRIMARY KEY (`AnswerID`),
  CONSTRAINT `FKryr8kigvj5aw9w6ilkvmrht5q`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `surveyquestions` (`QuestionID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKryr8kigvj5aw9w6ilkvmrht5q` ON `answers` (`QuestionID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `appointmenthistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appointmenthistory` ;

CREATE TABLE IF NOT EXISTS `appointmenthistory` (
  `HistoryID` VARCHAR(36) NOT NULL,
  `Action` ENUM('Cancelled', 'Created', 'Updated') NOT NULL,
  `AppointmentID` VARCHAR(36) NOT NULL,
  `ChangeDate` DATETIME(6) NULL DEFAULT NULL,
  `ChangedBy` VARCHAR(36) NOT NULL,
  `Notes` TEXT NULL DEFAULT NULL,
  `Status` ENUM('Cancelled', 'Completed', 'Scheduled') NOT NULL,
  PRIMARY KEY (`HistoryID`),
  CONSTRAINT `FKqfi5e9pswtyy5778vcb291iu8`
    FOREIGN KEY (`AppointmentID`)
    REFERENCES `appointments` (`AppointmentID`),
  CONSTRAINT `FKt90w9bhrlqtxcxsjnujaxxxxv`
    FOREIGN KEY (`ChangedBy`)
    REFERENCES `users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKqfi5e9pswtyy5778vcb291iu8` ON `appointmenthistory` (`AppointmentID` ASC) VISIBLE;

CREATE INDEX `FKt90w9bhrlqtxcxsjnujaxxxxv` ON `appointmenthistory` (`ChangedBy` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `appointments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appointments` ;

CREATE TABLE IF NOT EXISTS `appointments` (
  `AppointmentID` VARCHAR(36) NOT NULL,
  `CheckInTime` DATETIME(6) NULL DEFAULT NULL,
  `CheckOutTime` DATETIME(6) NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `Notes` TEXT NULL DEFAULT NULL,
  `PsychologistID` VARCHAR(36) NOT NULL,
  `Status` ENUM('Cancelled', 'Completed', 'InProgress', 'Scheduled') NULL DEFAULT NULL,
  `StudentID` VARCHAR(36) NOT NULL,
  `TimeSlotsID` VARCHAR(36) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `AppointmentType` ENUM('Online', 'Offline') NULL DEFAULT NULL,
  `MeetingLink` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`AppointmentID`),
  CONSTRAINT `FK7j3kvglfjb20jbx6oubix5y9b`
    FOREIGN KEY (`StudentID`)
    REFERENCES `students` (`StudentID`),
  CONSTRAINT `FKayb7iw3wolqlcv0mjvub5bw2h`
    FOREIGN KEY (`TimeSlotsID`)
    REFERENCES `timeslots` (`TimeSlotsID`),
  CONSTRAINT `FKmily3f3tgg2d14poosui8nvyt`
    FOREIGN KEY (`PsychologistID`)
    REFERENCES `psychologists` (`PsychologistID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKmily3f3tgg2d14poosui8nvyt` ON `appointments` (`PsychologistID` ASC) VISIBLE;

CREATE INDEX `FK7j3kvglfjb20jbx6oubix5y9b` ON `appointments` (`StudentID` ASC) VISIBLE;

CREATE INDEX `FKayb7iw3wolqlcv0mjvub5bw2h` ON `appointments` (`TimeSlotsID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `blog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog` ;

CREATE TABLE IF NOT EXISTS `blog` (
  `BlogID` VARCHAR(36) NOT NULL,
  `Content` TEXT NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(36) NULL DEFAULT NULL,
  `Title` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`BlogID`),
  CONSTRAINT `FKcybsisx9ue26pxjyrqfma19tc`
    FOREIGN KEY (`CreatedBy`)
    REFERENCES `users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKcybsisx9ue26pxjyrqfma19tc` ON `blog` (`CreatedBy` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categories` ;

CREATE TABLE IF NOT EXISTS `categories` (
  `CategoryID` VARCHAR(36) NOT NULL,
  `CategoryName` ENUM('Anxiety', 'Depression', 'Stress') NOT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `notifications` ;

CREATE TABLE IF NOT EXISTS `notifications` (
  `NotificationID` VARCHAR(36) NOT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsRead` BIT(1) NULL DEFAULT NULL,
  `Message` TEXT NOT NULL,
  `Title` VARCHAR(255) NOT NULL,
  `Type` ENUM('Appointment', 'Survey', 'Program', 'Done') NOT NULL,
  `UserID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`NotificationID`),
  CONSTRAINT `FK689wccaxeicnjy9vjaqks20ya`
    FOREIGN KEY (`UserID`)
    REFERENCES `users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK689wccaxeicnjy9vjaqks20ya` ON `notifications` (`UserID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `parents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parents` ;

CREATE TABLE IF NOT EXISTS `parents` (
  `ParentID` VARCHAR(36) NOT NULL,
  `UserID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ParentID`),
  CONSTRAINT `FKj0gwsij677b838ipqcmrclxhy`
    FOREIGN KEY (`UserID`)
    REFERENCES `users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKj0gwsij677b838ipqcmrclxhy` ON `parents` (`UserID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `programparticipation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `programparticipation` ;

CREATE TABLE IF NOT EXISTS `programparticipation` (
  `ParticipationID` VARCHAR(36) NOT NULL,
  `EndDate` DATE NULL DEFAULT NULL,
  `ProgramID` VARCHAR(36) NOT NULL,
  `StartDate` DATE NOT NULL,
  `Status` ENUM('Cancelled', 'Completed', 'Joined') NOT NULL,
  `StudentID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ParticipationID`),
  CONSTRAINT `FK19bqmcxun4kulmgtpwlhlf65i`
    FOREIGN KEY (`ProgramID`)
    REFERENCES `programs` (`ProgramID`),
  CONSTRAINT `FKcqkowhb5ekatyig1sjvrkj6ba`
    FOREIGN KEY (`StudentID`)
    REFERENCES `students` (`StudentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK19bqmcxun4kulmgtpwlhlf65i` ON `programparticipation` (`ProgramID` ASC) VISIBLE;

CREATE INDEX `FKcqkowhb5ekatyig1sjvrkj6ba` ON `programparticipation` (`StudentID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `programs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `programs` ;

CREATE TABLE IF NOT EXISTS `programs` (
  `ProgramID` VARCHAR(36) NOT NULL,
  `Category` ENUM('Assessment', 'Cognitive', 'Counseling', 'Emotional', 'LifeSkills', 'Physical', 'Prevention', 'SelfHelp', 'Social', 'SupportGroup', 'Wellness') NOT NULL,
  `CreatedAt` DATETIME(6) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `Duration` INT NULL DEFAULT NULL,
  `ManagedByStaffID` VARCHAR(36) NOT NULL,
  `MeetingLink` VARCHAR(255) NULL DEFAULT NULL,
  `NumberParticipants` INT NULL DEFAULT NULL,
  `ProgramName` VARCHAR(100) NOT NULL,
  `StartDate` DATE NULL DEFAULT NULL,
  `Status` ENUM('Active', 'Inactive') NOT NULL,
  `AppointmentType` ENUM('Offline', 'Online') NOT NULL,
  PRIMARY KEY (`ProgramID`),
  CONSTRAINT `FKjaji8bkpu5s9s6vdystf4gusg`
    FOREIGN KEY (`ManagedByStaffID`)
    REFERENCES `users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKjaji8bkpu5s9s6vdystf4gusg` ON `programs` (`ManagedByStaffID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `programschedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `programschedule` ;

CREATE TABLE IF NOT EXISTS `programschedule` (
  `ScheduleID` VARCHAR(36) NOT NULL,
  `DayOfWeek` VARCHAR(10) NOT NULL,
  `EndTime` TIME NOT NULL,
  `ProgramID` VARCHAR(36) NOT NULL,
  `StartTime` TIME NOT NULL,
  PRIMARY KEY (`ScheduleID`),
  CONSTRAINT `FK7cmhqcejobhnshmb1eeiok17u`
    FOREIGN KEY (`ProgramID`)
    REFERENCES `programs` (`ProgramID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK7cmhqcejobhnshmb1eeiok17u` ON `programschedule` (`ProgramID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `programtags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `programtags` ;

CREATE TABLE IF NOT EXISTS `programtags` (
  `ProgramId` VARCHAR(36) NOT NULL,
  `TagId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ProgramId`, `TagId`),
  CONSTRAINT `FKqe3rsyoj9xkw039g2gl1wkfuh`
    FOREIGN KEY (`ProgramId`)
    REFERENCES `programs` (`ProgramID`),
  CONSTRAINT `FKsf4tt0sadfbmidngtelynbbpl`
    FOREIGN KEY (`TagId`)
    REFERENCES `tags` (`TagID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKsf4tt0sadfbmidngtelynbbpl` ON `programtags` (`TagId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `psychologists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psychologists` ;

CREATE TABLE IF NOT EXISTS `psychologists` (
  `PsychologistID` VARCHAR(36) NOT NULL,
  `Specialization` VARCHAR(100) NULL DEFAULT NULL,
  `Status` ENUM('Active', 'On Leave', 'Inactive') NOT NULL,
  `UserID` VARCHAR(36) NOT NULL,
  `YearsOfExperience` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PsychologistID`),
  CONSTRAINT `FKk8ad9rs4e4wbhcf7nxvf1c16n`
    FOREIGN KEY (`UserID`)
    REFERENCES `users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKk8ad9rs4e4wbhcf7nxvf1c16n` ON `psychologists` (`UserID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `refreshtoken`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refreshtoken` ;

CREATE TABLE IF NOT EXISTS `refreshtoken` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ExpiresAt` DATETIME(6) NOT NULL,
  `HashedToken` VARCHAR(255) NOT NULL,
  `UserID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKpxtlubptdust15wrm4k48fr4i`
    FOREIGN KEY (`UserID`)
    REFERENCES `users` (`UserID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKpxtlubptdust15wrm4k48fr4i` ON `refreshtoken` (`UserID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `studentnotes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studentnotes` ;

CREATE TABLE IF NOT EXISTS `studentnotes` (
  `NoteID` VARCHAR(36) NOT NULL,
  `AnxietyScore` INT NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DepressionScore` INT NULL DEFAULT NULL,
  `NoteText` TEXT NOT NULL,
  `NoteType` ENUM('General', 'Behavior', 'Academic', 'Emotional') NOT NULL,
  `PsychologistID` VARCHAR(36) NOT NULL,
  `StressScore` INT NULL DEFAULT NULL,
  `StudentID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`NoteID`),
  CONSTRAINT `FK7cr25o4fgjtovrntuil0rygo4`
    FOREIGN KEY (`PsychologistID`)
    REFERENCES `psychologists` (`PsychologistID`),
  CONSTRAINT `FKc3e9ixqrsmg11ssye7htjg0sa`
    FOREIGN KEY (`StudentID`)
    REFERENCES `students` (`StudentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK7cr25o4fgjtovrntuil0rygo4` ON `studentnotes` (`PsychologistID` ASC) VISIBLE;

CREATE INDEX `FKc3e9ixqrsmg11ssye7htjg0sa` ON `studentnotes` (`StudentID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students` ;

CREATE TABLE IF NOT EXISTS `students` (
  `StudentID` VARCHAR(36) NOT NULL,
  `AnxietyScore` INT NULL DEFAULT NULL,
  `ClassName` VARCHAR(20) NULL DEFAULT NULL,
  `DepressionScore` INT NULL DEFAULT NULL,
  `Grade` INT NULL DEFAULT NULL,
  `ParentID` VARCHAR(36) NOT NULL,
  `SchoolName` VARCHAR(100) NULL DEFAULT NULL,
  `StressScore` INT NULL DEFAULT NULL,
  `UserID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`StudentID`),
  CONSTRAINT `FKaengiastf6jkwmemijj3g2onv`
    FOREIGN KEY (`UserID`)
    REFERENCES `users` (`UserID`),
  CONSTRAINT `FKciyagwdb0nowj7f0dyoia1k3t`
    FOREIGN KEY (`ParentID`)
    REFERENCES `parents` (`ParentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKciyagwdb0nowj7f0dyoia1k3t` ON `students` (`ParentID` ASC) VISIBLE;

CREATE INDEX `FKaengiastf6jkwmemijj3g2onv` ON `students` (`UserID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `surveyquestions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `surveyquestions` ;

CREATE TABLE IF NOT EXISTS `surveyquestions` (
  `QuestionID` VARCHAR(36) NOT NULL,
  `CategoryID` VARCHAR(36) NULL DEFAULT NULL,
  `QuestionText` TEXT NOT NULL,
  `SurveyID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`QuestionID`),
  CONSTRAINT `FK3mu1ylyqne2p4vboi456v9phv`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `categories` (`CategoryID`),
  CONSTRAINT `FKb3qeg2ym9kg6byybvra3mql58`
    FOREIGN KEY (`SurveyID`)
    REFERENCES `surveys` (`SurveyID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK3mu1ylyqne2p4vboi456v9phv` ON `surveyquestions` (`CategoryID` ASC) VISIBLE;

CREATE INDEX `FKb3qeg2ym9kg6byybvra3mql58` ON `surveyquestions` (`SurveyID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `surveyresults`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `surveyresults` ;

CREATE TABLE IF NOT EXISTS `surveyresults` (
  `ResultID` VARCHAR(36) NOT NULL,
  `AnswerID` VARCHAR(36) NOT NULL,
  `QuestionID` VARCHAR(36) NOT NULL,
  `StudentID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ResultID`),
  CONSTRAINT `FK678llvs17bf7jg075j6lh9e1q`
    FOREIGN KEY (`StudentID`)
    REFERENCES `students` (`StudentID`),
  CONSTRAINT `FK8t68w18aa6owt2opherlwv9vk`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `surveyquestions` (`QuestionID`),
  CONSTRAINT `FKjs72wj2vwxl45cg2walj44dg5`
    FOREIGN KEY (`AnswerID`)
    REFERENCES `answers` (`AnswerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKjs72wj2vwxl45cg2walj44dg5` ON `surveyresults` (`AnswerID` ASC) VISIBLE;

CREATE INDEX `FK8t68w18aa6owt2opherlwv9vk` ON `surveyresults` (`QuestionID` ASC) VISIBLE;

CREATE INDEX `FK678llvs17bf7jg075j6lh9e1q` ON `surveyresults` (`StudentID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `surveys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `surveys` ;

CREATE TABLE IF NOT EXISTS `surveys` (
  `SurveyID` VARCHAR(36) NOT NULL,
  `CategoryID` VARCHAR(36) NOT NULL,
  `CreatedAt` DATETIME(6) NOT NULL,
  `CreatedBy` VARCHAR(36) NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `Status` ENUM('Unfinished', 'Finished', 'Cancelled') NOT NULL,
  `SurveyName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`SurveyID`),
  CONSTRAINT `FKk4lykft9ydt37leirifqmsalt`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `categories` (`CategoryID`),
  CONSTRAINT `FKo76oxa2c3q56tr77aknoeqjck`
    FOREIGN KEY (`CreatedBy`)
    REFERENCES `users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKk4lykft9ydt37leirifqmsalt` ON `surveys` (`CategoryID` ASC) VISIBLE;

CREATE INDEX `FKo76oxa2c3q56tr77aknoeqjck` ON `surveys` (`CreatedBy` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tags` ;

CREATE TABLE IF NOT EXISTS `tags` (
  `TagID` VARCHAR(36) NOT NULL,
  `TagName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`TagID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `timeslots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timeslots` ;

CREATE TABLE IF NOT EXISTS `timeslots` (
  `TimeSlotsID` VARCHAR(36) NOT NULL,
  `CreatedAt` DATETIME(6) NOT NULL,
  `EndTime` TIME NOT NULL,
  `SlotDate` DATE NOT NULL,
  `SlotNumber` INT NOT NULL,
  `StartTime` TIME NOT NULL,
  `Status` ENUM('Available', 'Booked') NOT NULL,
  `PsychologistID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`TimeSlotsID`),
  CONSTRAINT `FK9ece0eaadgo17qqksrlvif0gh`
    FOREIGN KEY (`PsychologistID`)
    REFERENCES `psychologists` (`PsychologistID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK9ece0eaadgo17qqksrlvif0gh` ON `timeslots` (`PsychologistID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `userlogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `userlogs` ;

CREATE TABLE IF NOT EXISTS `userlogs` (
  `LogID` VARCHAR(36) NOT NULL,
  `IPAddress` VARCHAR(50) NULL DEFAULT NULL,
  `LoginTime` DATETIME(6) NULL DEFAULT NULL,
  `UserID` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`LogID`),
  CONSTRAINT `FKct2vgnj582notleijgl3l3mkj`
    FOREIGN KEY (`UserID`)
    REFERENCES `users` (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKct2vgnj582notleijgl3l3mkj` ON `userlogs` (`UserID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `UserID` VARCHAR(36) NOT NULL,
  `CreatedAt` DATETIME(6) NOT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `FullName` VARCHAR(100) NOT NULL,
  `Gender` ENUM('Male', 'Female', 'Other') NULL DEFAULT NULL,
  `IsVerified` BIT(1) NOT NULL,
  `PasswordHash` VARCHAR(255) NOT NULL,
  `PhoneNumber` VARCHAR(15) NULL DEFAULT NULL,
  `ResetToken` VARCHAR(255) NULL DEFAULT NULL,
  `ResetTokenExpiry` DATETIME(6) NULL DEFAULT NULL,
  `Role` ENUM('MANAGER', 'PARENT', 'PSYCHOLOGIST', 'STUDENT') NOT NULL,
  `TokenExpiration` DATETIME(6) NOT NULL,
  `UpdatedAt` DATETIME(6) NOT NULL,
  `Username` VARCHAR(50) NOT NULL,
  `VerificationToken` VARCHAR(255) NOT NULL,
  `reset_token` VARCHAR(255) NULL DEFAULT NULL,
  `reset_token_expiry` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UK9cw87ffd4i55ki0qpkwu63er` ON `users` (`Username` ASC) VISIBLE;

CREATE UNIQUE INDEX `UKjdfr6kjrxekx1j5vrr77rp44t` ON `users` (`Email` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
