spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      pool-name: HikariCP
      minimum-idle: 4
      maximum-pool-size: 10
      idle-timeout: 120000
      max-lifetime: 1800000
      keepalive-time: 120000

  jpa:
    properties:
      hibernate:
        physical_naming_strategy: com.healthy.backend.init.PascalCaseNamingStrategy
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false

  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"
    allow-credentials: true
    max-age: 3600

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  address: 0.0.0.0
  port: 8080
  tomcat:
    threads:
      min-spare: 2
      max: 5
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml
    min-response-size: 1024

hibernate:
  transaction:
    jta:
      platform: org.hibernate.service.jta.platform.internal.AtomikosJtaPlatform

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.zaxxer.hikari: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
  refresh-token:
    expiration: 604800000

app:
  url: https://api.cybriadev.com/
