server:
  port: 8080
  servlet:
    context-path: /healthy
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/swp391"
    username: root
    password: 123456
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true

