spring:
  config:
    activate:
      on-profile: prod
      
  
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration
      - org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration
      - org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration
      - org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration
      - org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration
      - org.springframework.boot.autoconfigure.jta.JtaAutoConfiguration
    
  mvc:
    throw-exception-if-no-handler-found: true
    
  security:
    filter:
      dispatcher-types: REQUEST

  # Database configuration optimized for idle state
  datasource:
    url: ${DATABASE_URL}?serverTimezone=Asia/Ho_Chi_Minh&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      pool-name: HikariCP
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 300000 # 5 minutes
      max-lifetime: 1800000 # 30 minutes
      connection-timeout: 30000 # 30 seconds
      validation-timeout: 5000 # 5 seconds
      keepalive-time: 60000 # 1 minute
      leak-detection-threshold: 0 # 0 seconds

  # Common timeZone setting
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    parser:
      allow-single-quotes: true
      
  # JPA/Hibernate configuration
  jpa:
    properties:
      hibernate:
        physical_naming_strategy: com.healthy.backend.init.PascalCaseNamingStrategy
        # Memory optimized JDBC settings
        jdbc:
          batch_size: 10
          fetch_size: 50
          batch_versioned_data: false
        
        # Query and plan cache optimization
        query:
          in_clause_parameter_padding: true
          plan_cache_max_size: 32
          plan_parameter_metadata_max_size: 16
        
        # Collection and relationship optimization
        max_fetch_depth: 4
        default_batch_fetch_size: 10
        collection:
          fetch:
            batch_size: 10
        
        # Memory management settings
        order_inserts: true
        order_updates: true
        connection:
          handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
          provider_disables_autocommit: false
          release_mode: after_transaction
        
        # Updated metadata access setting
        boot:
          allow_jdbc_metadata_access: false
        
        # Dialect setting (explicit for production)
        dialect: org.hibernate.dialect.MySQLDialect
        
        # Disable unnecessary features
        session:
          events:
            log: false
        generate_statistics: false
        cache:
          use_second_level_cache: false
          use_query_cache: false
    
    # JPA specific settings
      jakarta:
        persistence:
          persistence-unit:
            transaction-type: RESOURCE_LOCAL
          flush:
            mode: AUTO
            
    hibernate:
      ddl-auto: update
    open-in-view: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: false
    
  task:
    execution:
      pool:
        core-size: 2
        max-size: 8

  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"
    allow-credentials: true
    max-age: 3600

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      

  # Disable unnecessary features in production
  springdoc:
    swagger-ui:
      customJs: /static/custom-swagger.js
      customCss: /static/style.css
      defaultModelsExpandDepth: -1
      disable-swagger-default-response-messages: true
      lazy-load: true
      docExpansion: none
      filter: true
      use-root-path: true
      enabled: true  # Disable in production
    override-with-generic-response: false
    cache:
      disabled: true
    writer-with-default-pretty-printer: false
    api-docs:
      enabled: true

# Server settings
server:
  address: 0.0.0.0
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml
    min-response-size: 1024
  undertow:
    io-threads: 2
    worker-threads: 4
    buffer-size: 512
    websocket:
      buffer-pool: 512
    direct-buffers: true

# Production logging configuration
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.zaxxer.hikari: INFO
    org.hibernate: INFO
    com.healthy.backend: INFO
    io.undertow.websockets.jsr: ERROR  # Suppress websocket warnings
    org.springframework.security.config.annotation.authentication.configuration: ERROR  # Suppress authentication warnings
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} : %msg%n"

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
  refresh-token:
    expiration: 604800000

app:
  url: https://api.cybriadev.com/