spring:
  datasource:
    url: jdbc:mysql://mysql-3306-kaitran2205-b03e.f.aivencloud.com:28719/SWP391Healthy
    username: avnadmin
    password: AVNS_RF7LRtmAdy-lyylms5i
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    open-in-view: false  # Prevents memory leaks (Best practice)
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-specific-password
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  hikari:
    pool-name: HikariCP
    minimum-idle: 1       # Keep only 1 idle connection to save memory
    maximum-pool-size: 2   # Limited DB connections (prevents overuse)
    idle-timeout: 30000    # Close idle connections quickly (30s)
    max-lifetime: 600000   # Prevent stale connections (10 min)
    keepalive-time: 60000  # Avoid connection timeouts (1 min)
  cors:
    configuration:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      exposed-headers: "*"
      allow-credentials: true
      max-age: 3600
  security:
    user:
      password:
        encoder:
          bcrypt:
            strength: 10  # Reduce from 16 to save CPU cycles
  physical_naming_strategy: com.healthy.BackEnd.init.PascalCaseNamingStrategy

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
  refresh-token:
    expiration: 604800000

logging:
  level:
    org.springframework: INFO  # Reduce log level to save CPU
    com.zaxxer.hikari: WARN    # Only log critical DB pool issues
    org.hibernate.SQL: WARN     # Reduce excessive SQL logging
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

server:
  port: 8080
  tomcat:
    threads:
      min-spare: 2
      max: 5  # Small max thread count to match low CPU
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml
    min-response-size: 1024

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  health:
    defaults:
      enabled: false
  info:
    env:
      enabled: true
  logging:
    level:
      org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR