spring:
  config:
    activate:
      on-profile: prod
      
  jmx:
    enabled: false
  main:
    web-application-type: servlet
    lazy-initialization: true
    banner-mode: off
    allow-bean-definition-overriding: false
    allow-circular-references: false
    cloud-platform: none
    
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
    
  security:
    filter:
      dispatcher-types: REQUEST

  # Database configuration optimized for idle state
  datasource:
    url: ${DATABASE_URL}?serverTimezone=Asia/Ho_Chi_Minh&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      pool-name: HikariCP
      minimum-idle: 1
      maximum-pool-size: 2
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      keepalive-time: 0
      leak-detection-threshold: 0

  # Common timeZone setting
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    parser:
      allow-single-quotes: true
      
  # JPA/Hibernate configuration
  jpa:
    properties:
      hibernate:
        physical_naming_strategy: com.healthy.backend.init.PascalCaseNamingStrategy
        jdbc:
          batch_size: 10
        order_updates: true
        batch_versioned_data: true
        default_batch_fetch_size: 20
        query:
          plan_cache_max_size: 64
          plan_parameter_metadata_max_size: 32
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

  task:
    execution:
      pool:
        core-size: 1
        max-size: 5

  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"
    allow-credentials: true
    max-age: 3600

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      

  # Disable unnecessary features in production
  springdoc:
    swagger-ui:
      customJs: /static/custom-swagger.js
      customCss: /static/style.css
      defaultModelsExpandDepth: -1
      disable-swagger-default-response-messages: true
      lazy-load: true
      docExpansion: none
      filter: true
      use-root-path: true
    override-with-generic-response: false
    cache:
      disabled: true
    writer-with-default-pretty-printer: false

    api-docs:
      enabled: false
    swagger-ui:
      enabled: false

# Server settings
server:
  address: 0.0.0.0
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml
    min-response-size: 1024
  undertow:
    io-threads: 1
    worker-threads: 2
    buffer-size: 1024KB
    direct-buffers: false
    max-http-post-size: 10485760

# Hibernate settings
hibernate:
  transaction:
    jta:
      platform: org.hibernate.service.jta.platform.internal.AtomikosJtaPlatform

# Production logging configuration
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR

    org.hibernate: INFO
    com.healthy.backend: INFO

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
  refresh-token:
    expiration: 604800000

app:
  url: https://api.cybriadev.com/
