server:
  # Allow external access on render.com
  address: 0.0.0.0
  port: 8080
  tomcat:
    threads:
      min-spare: 2
      # Small max thread count to match low CPU
      max: 5
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml
    min-response-size: 1024

spring:
  profiles:
#    active: dev
    active: prod

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    open-in-view: false

  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false

  cors:
    configuration:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      exposed-headers: "*"
      allow-credentials: true
      max-age: 3600

  security:
    user:
      password:
        encoder:
          bcrypt:
            strength: 10

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  health:
    defaults:
      enabled: false
  info:
    env:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.zaxxer.hikari: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR