spring:
  config:
    activate:
      on-profile: prod
      
  jmx:
    enabled: false
    
  jvm:
    gc:
      log-file-rotation: true
      log-detail: true
      log-file: /tmp/gc.log
      log-file-size: 20MB
      log-file-count: 5

  main:
    web-application-type: servlet
    lazy-initialization: true
    banner-mode: off
    allow-bean-definition-overriding: false
    allow-circular-references: false
    cloud-platform: none
    register-shutdown-hook: false
  
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration
      - org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration
      - org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration

  resources:
    add-mappings: false
    cache:
      period: 0
      control:
        max-age: 0
    
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 5000
    
  security:
    filter:
      dispatcher-types: REQUEST
    basic:
      enabled: false

  # Database configuration optimized for speed
  datasource:
    url: ${DATABASE_URL}?serverTimezone=Asia/Ho_Chi_Minh&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      keepalive-time: 60000
      leak-detection-threshold: 60000
      register-mbeans: false
      allow-pool-suspension: false
      initialization-fail-timeout: 1
      validation-query: SELECT 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  # Common timeZone setting
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    parser:
      allow-single-quotes: true
      
  # JPA/Hibernate configuration optimized for speed
  jpa:
    properties:
      hibernate:
        physical_naming_strategy: com.healthy.backend.init.PascalCaseNamingStrategy
        jdbc:
          batch_size: 50
          fetch_size: 100
          batch_versioned_data: true
        
        query:
          in_clause_parameter_padding: true
          plan_cache_max_size: 128
          plan_parameter_metadata_max_size: 32
        
        max_fetch_depth: 2
        default_batch_fetch_size: 50
        collection:
          fetch:
            batch_size: 50
        
        order_inserts: true
        order_updates: true
        connection:
          handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
          provider_disables_autocommit: false
          release_mode: after_transaction
        
        dialect: org.hibernate.dialect.MySQLDialect
        
        session:
          events:
            log: false
        generate_statistics: false
        cache:
          use_second_level_cache: false
          use_query_cache: false
        
        transaction:
          auto_close_session: false
          coordinator_class: jdbc
    
    hibernate:
      ddl-auto: update
    open-in-view: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: false
    
  task:
    execution:
      pool:
        core-size: 4
        max-size: 16
        queue-capacity: 200
        keep-alive: 60s

  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    exposed-headers: "*"
    allow-credentials: true
    max-age: 3600

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.timeout: 5000
      mail.smtp.connectiontimeout: 5000
      mail.smtp.writetimeout: 5000

springdoc:
  swagger-ui:
    customJs: /static/custom-swagger.js
    customCss: /static/style.css
    defaultModelsExpandDepth: -1
    disable-swagger-default-response-messages: true
    lazy-load: true
    docExpansion: none
    filter: true
    use-root-path: true
  override-with-generic-response: false
  cache:
    disabled: true
  writer-with-default-pretty-printer: false

# Server settings optimized for speed
server:
  address: 0.0.0.0
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml
    min-response-size: 1024
  undertow:
    io-threads: 4
    worker-threads: 8
    buffer-size: 2048
    websocket:
      buffer-pool: 2048
    direct-buffers: true
    no-request-timeout: 60000
    max-parameters: 1000
    max-headers: 200
    max-cookies: 200
    allow-encoded-slash: true
    decode-url: true
    url-charset: UTF-8
    always-set-keep-alive: true
    max-entity-size: 10485760
    http2-enabled: true

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.zaxxer.hikari: INFO
    org.hibernate: INFO
    com.healthy.backend: INFO
    io.undertow.websockets.jsr: ERROR
    org.springframework.security.config.annotation.authentication.configuration: ERROR
    org.springframework.web: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} : %msg%n"

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
  refresh-token:
    expiration: 604800000

app:
  url: https://api.cybriadev.com/