package com.healthy.backend.enums;

public enum ProgramTags {

    // Stress-Related
    STRESS,
    TEST_STRESS,
    ACADEMIC_STRESS,
    WORK_STRESS,
    FINANCIAL_STRESS,
    RELATIONSHIP_STRESS,
    SELF_IMPROVEMENT_STRESS,
    STRESS_MANAGEMENT,

    // Anxiety & Depression
    ANXIETY,
    TEST_ANXIETY,
    DEPRESSION,
    TEST_DEPRESSION,

    // Mental Health & Well-being
    MENTAL_HEALTH,
    EMOTIONAL_INTELLIGENCE,
    EMOTIONAL_REGULATION,
    EMOTIONAL_EXPRESSION,
    MINDFULNESS,
    MEDITATION,
    RELAXATION,
    SLEEP,
    WELLNESS,
    HEALTH,
    SELF_HEALTH,

    // Self-Improvement & Personal Growth
    SELF_CARE,
    SELF_IMPROVEMENT,
    SELF_AWARENESS,
    SELF_DISCIPLINE,
    SELF_REFLECTION,
    SELF_MANAGEMENT,
    SELF_CONTROL,
    SELF_ACCEPTANCE,
    SELF_ESTEEM,
    CONFIDENCE,
    MOTIVATION,
    PRODUCTIVITY,
    RESILIENCE,
    COPING_SKILLS,
    PROBLEM_SOLVING,
    DECISION_MAKING,
    TIME_MANAGEMENT,
    BOUNDARIES,
    PERSONAL_DEVELOPMENT,

    // Relationships & Social Support
    RELATIONSHIP,
    RELATIONSHIP_HEALTH,
    RELATIONSHIP_BUILDING,
    ACADEMIC_RELATIONSHIP,
    WORK_RELATIONSHIP,
    FINANCIAL_RELATIONSHIP,
    SOCIAL_SUPPORT,
    SOCIAL_CONNECTIVITY,
    SOCIAL_INTERACTION,
    COMMUNITY,
    COMMUNITY_ENGAGEMENT,
    COMMUNITY_INVOLVEMENT,
    PEER_SUPPORT,

    // Physical Health & Lifestyle
    PHYSICAL_HEALTH,
    EXERCISE,

    // Addiction & Disorders
    ADDICTION,
    EATING_DISORDER,
    BODY_IMAGE,

    // Support & Healing
    SUPPORT,
    HEALING,
    GRIEF
}